### ISSUE TITLE
neurochemcpp_iface.h

### ISSUE THREAD

**Issue by virginia2019** [chemalot/openmm-ani#1]
Hi, thank you for making this available! When I run make, I receive a fatal error because neurochemcpp_iface.h is missing. Do you know where I can access this file?

tools/openmm-ani/openmmapi/src/ANIForceImpl.cpp:39:32: fatal error: neurochemcpp_iface.h: No such file or directory
compilation terminated.
CMakeFiles/OpenMMANI.dir/build.make:75: recipe for target 'CMakeFiles/OpenMMANI.dir/openmmapi/src/ANIForceImpl.cpp.o' failed
make[2]: *** [CMakeFiles/OpenMMANI.dir/openmmapi/src/ANIForceImpl.cpp.o] Error 1
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/OpenMMANI.dir/all' failed
make[1]: *** [CMakeFiles/OpenMMANI.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

Thanks!
-VA

**Comment by bgobbi** [comment]
Hi Virginia,
I got the neurochemcpp_iface.h file from the ASE_ANI package. I am currently using the centos_cuda10_py36 branch, but you will need to have the correct library for your python version and your OS version.
https://github.com/isayev/ASE_ANI/blob/centos_cuda10_py36/include/neurochemcpp_iface.h

Please reach out to the ASE_ANI project for specifics. Getting this right is essential to get this plugin working.
