### ISSUE TITLE
Make printing of the results of ANI force optional

### ISSUE THREAD

**Issue by Clownshift** [chemalot/openmm-ani#4]
I think currently, the user needs to dig rather deep into the source to deactivate the printing of the results of ANIForce. Is that correct?

I believe the PRINT_RESULTS variable, would need to be changed and then it would need to be recompiled:

https://github.com/chemalot/openmm-ani/blob/master/platforms/cuda/src/CudaANIKernels.cpp

Please feel free to correct me, if I am wrong.

Depending on the simulations, printing these results may potentially lead to A LOT of on-screen printing (or wherever this may be directed by the user).

I think it would be nice to make this an input argument for the relevant functions. Which can then can be set flexibly by the user when calling the function.

**Comment by bgobbi** [comment]
Yes you are correct.

 I will make the PRINT_RESULTS  default to 0. In my opinion this is just a debugging feature as I do not expect anybody to use the output as generated with PRINT_RESULTS  1.

**Comment by Clownshift** [comment]
Alright thanks for your comment. That also clarifies your comment in #5 for me. 

What do you think about introducing a debug flag for compilation?
With idfef  or so.

**Comment by bgobbi** [comment]
I would be fine with that, if you like to send a ,merge request.
