### ISSUE TITLE
Ensemble energies are printed to stderr

### ISSUE THREAD

**Issue by Clownshift** [chemalot/openmm-ani#5]
So are the atomymbols and the atompositions.

In my opinion these properties should be printed to stdout. Is there a specific reason that they are printed to stderr?

E.g. in line:
https://github.com/chemalot/openmm-ani/blob/0b78ed577c0873e4eb7eecffa4628e08cc8478bf/platforms/cuda/src/CudaANIKernels.cpp#L123

**Comment by bgobbi** [comment]
Thanks for the comment. I do not agree with this though. Printing to stdout from a library will prevent this library to be used in applications that intend to create output in a specific format on stdout. This output was only intended to be used for debugging.
